version: '3'

services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-8.2}-v4-cli-node22
    environment:
      TYPO3_VERSION: ${TYPO3_VERSION:-^13.4}
      TYPO3_API_TOKEN:
      TYPO3_API_PASSWORD:
      TYPO3_API_USERNAME:
      TAG:
      typo3DatabaseHost: mysql
      typo3DatabaseName: typo3
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
      PHP_EXTENSIONS: gd intl
      HTTP_HOST: dummy
    depends_on:
      - mysql
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    tmpfs:
      - /var/lib/mysql
